//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Localization.SourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Localization.SourceFiles.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations!  Your organization has been activated.
        /// </summary>
        internal static string EMAIL_ACTIVE_ORGANIZATION_TITLE {
            get {
                return ResourceManager.GetString("EMAIL_ACTIVE_ORGANIZATION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password successfully.
        /// </summary>
        internal static string EMAIL_CHANGED_PASSWORD_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("EMAIL_CHANGED_PASSWORD_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invitation.
        /// </summary>
        internal static string EMAIL_INVITE_USER_SUBJECT {
            get {
                return ResourceManager.GetString("EMAIL_INVITE_USER_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {InviteeName} has invited you to work with them in.
        /// </summary>
        internal static string EMAIL_INVITE_USER_TITLE {
            get {
                return ResourceManager.GetString("EMAIL_INVITE_USER_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login code.
        /// </summary>
        internal static string EMAIL_LOGIN_CODE_TITLE {
            get {
                return ResourceManager.GetString("EMAIL_LOGIN_CODE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your email address.
        /// </summary>
        internal static string EMAIL_REQUEST_CHANGE_IN_PROFILE_TITLE {
            get {
                return ResourceManager.GetString("EMAIL_REQUEST_CHANGE_IN_PROFILE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reset your password.
        /// </summary>
        internal static string EMAIL_REQUEST_CHANGE_PASSWORD_TITLE {
            get {
                return ResourceManager.GetString("EMAIL_REQUEST_CHANGE_PASSWORD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about your Task Management Software.
        /// </summary>
        internal static string EMAIL_TUTORIAL_USER_SUBJECT {
            get {
                return ResourceManager.GetString("EMAIL_TUTORIAL_USER_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WELCOME.
        /// </summary>
        internal static string EMAIL_TUTORIAL_USER_TITLE {
            get {
                return ResourceManager.GetString("EMAIL_TUTORIAL_USER_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify your email address.
        /// </summary>
        internal static string EMAIL_VERIFICATION_TITLE {
            get {
                return ResourceManager.GetString("EMAIL_VERIFICATION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string EMAIL_WELCOME_TITLE {
            get {
                return ResourceManager.GetString("EMAIL_WELCOME_TITLE", resourceCulture);
            }
        }
    }
}
